---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Secure Women Chat Group"
keywords:    "security,women,community, slack"
description: "Public landing page for Secure Women chat group. Read code of conduct, request invite here.."
source_link: "http://securewomen.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:        '#111111'
  white:        '#f8f8f8'
  red:			'#E85B57'
  orange:		'#F59B5B'
  yellow:		'#F8D57A'
  lightgreen:	'#3EE965'
  darkgreen:	'#14C782'
  blue:			'#00C0FC'
  indigo:		'#5A81FF'
  purple:		'#5D19AF'

  mauve:        '#BDAEC6'
  darkmauve:    '#9C8AA5'
  lightblue2:   '#C1E0F7'
  pinkpurple:   '#583759'
  lightpurple:  '#421C52'
